<?php

return [
    'Adrar (أدرار)',
    'Chlef (الشلف)',
    'Laghouat (الأغواط)',
    'Oum El Bouaghi (أم البواقي)',
    'Batna (باتنة)',
    'Béjaïa (بجاية)',
    'Biskra (بسكرة)',
    'Béchar (بشار)',
    'Blida (البليدة)',
    'Bouïra (البويرة)',
    'Tamanrasset (تمنراست)',
    'Tébessa (تبسة)',
    'Tlemcen (تلمسان)',
    'Tiaret (تيارت)',
    'Tizi Ouzou (تيزي وزو)',
    'Algiers / Alger (الجزائر العاصمة)',
    'Djelfa (الجلفة)',
    'Jijel (جيجل)',
    'Sétif (سطيف)',
    'Saïda (سعيدة)',
    'Skikda (سكيكدة)',
    'Sidi Bel Abbès (سيدي بلعباس)',
    'Annaba (عنابة)',
    'Guelma (قالمة)',
    'Constantine (قسنطينة)',
    'Médéa (المدية)',
    'Mostaganem (مستغانم)',
    'M\'Sila (المسيلة)',
    'Mascara (معسكر)',
    'Ouargla (ورقلة)',
    'Oran (وهران)',
    'El Bayadh (البيض)',
    'Illizi (إليزي)',
    'Bordj Bou Arréridj (برج بوعريريج)',
    'Boumerdès (بومرداس)',
    'El Tarf (الطارف)',
    'Tindouf (تندوف)',
    'Tissemsilt (تيسمسيلت)',
    'El Oued (الوادي)',
    'Khenchela (خنشلة)',
    'Souk Ahras (سوق أهراس)',
    'Tipaza (تيبازة)',
    'Mila (ميلة)',
    'Aïn Defla (عين الدفلى)',
    'Naâma (النعامة)',
    'Aïn Témouchent (عين تيموشنت)',
    'Ghardaïa (غرداية)',
    'Relizane (غليزان)',
    'Timimoun (تيميمون)',
    'Bordj Badji Mokhtar (برج باجي مختار)',
    'Ouled Djellal (أولاد جلال)',
    'Béni Abbès (بني عباس)',
    'Aïn Salah (عين صالح)',
    'Aïn Guezzam (عين قزام)',
    'Touggourt (تقرت)',
    'Djanet (جانت)',
    'El M\'Ghair (المغير)',
    'El Menia (المنيعة)',
    'Aflou (آفلو)',
    'Barika (بريكة)',
    'El Kantara (القنطرة)',
    'Bir El Ater (بئر العاتر)',
    'El Aricha (العريشة)',
    'Ksar Chellala (قصر الشلالة)',
    'Aïn Oussera (عين وسارة)',
    'Messaad (مسعد)',
    'Ksar El Boukhari (قصر البخاري)',
    'Boussaâda (بوسعادة)',
    'El Abiodh Sidi Cheikh (الأبيض سيدي الشيخ)',
];

